### ISSUE TITLE
Rebel C-3PO now wrong point cost.

### ISSUE THREAD

**Issue by JediOswald** [guidokessels/xwing-data2#524]
When Republic C-3PO got its points cost corrected to be 6 points from 7, Rebel C-3PO also got listed as 6 points when he should still be 7.

**Comment by danrs** [comment]
FIxed in #525

**Comment by JediOswald** [comment]
Not fixed, R2-D7 Bot still displays Rebel C-3PO crew as 6 points instead of 7.

**Comment by JediOswald** [comment]
![3PO](https://user-images.githubusercontent.com/87926233/156799184-e9379594-8026-4e18-bb50-c6c839b90667.PNG)

**Comment by danrs** [comment]
#525 hasn’t been merged in yet but the fix is in that PR
